---
title: "Introduction"
output: pdf_document
bibliography: references.bib
---

# Introduction

IDK INTRO SENTENCE. In the recent years, the focus in diverse subfields of psychology has been shifting towards complexity, dynamics and within-person perspective in psychology [@hamaker2012]. Among other things, this shift has been facilitated by the growing availability of smartphones and wearables, which allow researchers to use the Experience Sampling Method (ESM) to collect intensive longitudinal data with a high level of ecological validity [@myin-germeys2018]. Intensive longitudinal data consist of repeated (self-report) measurements nested within individual participants [@larson2014experience]. The use of intensive longitudinal data considerably broadens the extent of research questions psychological researchers can investigate and statistical analyses they can conduct. Importantly, the multilevel structure of intensive longitudinal data allows researchers to investigate both within-person dynamic processes, and the individual differences therein between persons (CITE).One of the new research avenues that emerged with the growing popularity of intensive longitudinal data is the study of affect dynamics (for an overview, see @houben2015). The dynamic measures make use of the structure of intensive longitudinal data and take the fluctuating nature of affect/emotions into account.

Apart from dynamic measures such as emotional variance or instability, inertia (operationalised as autoregression in psychological studies using ESM) emerged as a dynamic measure that can contribute to the knowledge about emotional regulation [@kuppens2017]. The autoregressive (AR) parameter quantifies the degree to which the value of a process at time *t* is influenced by the lagged variable (i. e., the process value at a previous timepoint; usually, *t-1*). In other words, the AR parameter allows us to approximate to what degree the intensity of an emotion/affect is carried onto the intensity of the emotional experience at the subsequent timepoint (for the same emotion), and to what degree the process is influenced by other factors. The part of the process value that is not explained by the lagged variable is considered to be caused by *innovation*: the ensemble of (both within- and between-person factors) that have influenced the process at a given timepoint [@ariens2020]. Inertia is usually modeled using a multilevel autoregressive (MLAR) model [@koval2021]. Usually, the model has two levels: the wthin-person Level 1, in which the intra-person autoregressive process is modeled, and the between-person Level 2, in which the individual differences in the autoregressive parameter and intercept are modelled. A more detailed description of the model is described in the Methods section.

### Emotional inertia and psychological well-being 

Although some degree of inertia is to be expected in human emotional experiences, a high level of emotional inertia (i. e., a high temporal persistence of emotional states) has been linked to psychological maladjustment [@kuppens2010]. A negative emotion process with a high inertia can get caught in a self-reinforced feedback loop [also called *critical slowing down,* Leemput -@vandeleemput2014]. This causes the process to be partially resistant to both external influences and inner processes, including emotional regulation [@koval2015].

The evidence about the association between emotional inertia and the well-being/psychopathology spectrum has grown steadily over the last two decades. A recent meta-analysis indicated an association between emotioal inertia (of both positive and negative emotions) and psychological well-being/psychopathology [@houben2015]. More specifically, higher emotional inertia has been linked to lower well-being and higher ocurrence of depressive symptoms[@koval2016, @brose2015], bipolar disorder [@mneimne2018], and lower response of depression and anxiety symptoms to cognitive-behavioral therapy [@bosley2019].

However, a recent study demonstrated that when the affect intensity (i.e., the mean of the affective process) is taken into account in the regression model, the dynamic measures such as inertia, instability and variability no longer meaningfully contribute to the prediction of well-being and psychopathology [@dejonckheere2019]. Similarly, recent empirical studies did not show a significant association between inertia and depression/anxiety symptoms [@bosley2019] and borderline personality disorder [@houben2020]. One reason for this is the statistical overlap between the emotion intensity (i. e., the process mean), inertia, and the other dynamic measures [@koval2013; @bos2019].

### Problems with the estimation of inertia 

In addition to the statistical overlap between dynamic measures, another reason for the limited contribution of inertia to the prediction of psychopathology/well-being is the fact that the current ways of estimating emotional inertia from ESM data do not provide sufficient precision in the estimation of inertia. Wenzel & Brose [-@wenzel2022] show that the neglect of estimating reliability of inertia leads to an attenuation of its relation to depressive symptoms. When reliability is taken into account via multilevel dynamic structural equation modeling and inertia is modeled as latent, the inertia of negative affect contributes to the prediction of depressive symptoms even when the emotion mean is included in the model [@wenzel2022]. Furthermore, measurement decisions (such as the choice of items comprising the positive/negative affect composite measures), which are often made ad hoc in ESM research [@cloos2022], can lead to very different estimates of inertia.

More generally, low estimation precision will lead to the attenuation of the meaningful associations between inertia and other psychological constructs. Several simulation studies investigated the effect of varying parameters (such as number of participants and number of observations per participant) and assumption violations on measures related to the estimation precision of the MLAR(1) model. In the following sub-chapter, the evidence from simulation studies will be summarised.

### Evidence from simulation studies 

Jongerling et al. [-@jongerling2015] investigated the effect of modeling innovation variance as fixed (identical for all participants) instead of random. They found that modeling innovation as fixed when it differs across participants leads to a considerable bias in the estimation of the fixed AR effect. There is an upward bias (overestimation) present when the correlation between the individual AR effects and individual innovation variances is positive, and vice versa. Additionally, Jongerling et al. point out that using the person-means to center the lagged predictor variable leads to a downward bias in the estimation of the fixed AR effect. The effect of person-mean centering the predictor on the estimation performance of the MLAR model was further studied by Hamaker & Grasman [@hamaker2015]. Their simulation study confirmed that person-mean centering leads to an underestimation of the fixed autoregressive effect, especially when the number of timepoints per participant *(T.obs)* is low. Still, they recommend using person-mean centering when one is interested in the effect of a between-person predictor on inertia.

In their simulation study comparing the maximum likelihoood and Bayesian approaches to estimating the MLAR model, Krone et al. [-@krone2016] show that the two estimation procedures have a very similar performance. Furthermore, a higher *T.obs* leads to more precise estimates, while the effect of *N* on the estimation performance is small. They also show that a higher variance of the random AR effects lead to a lesser estimation precision, and that the estimation bias gets smaller when the real fixed AR effect increases. Liu [-@liu2017] assessed how violating the normality of the random AR effect distribution influences the estimation performance of the MLAR model. The different distributions of the random AR effects were found to only have a small effect on the estimation performance.

TODO: Gistelinck.

While the simulation studies mentioned above provide an extensive body of evidence about the statistical properties of the MLAR model under different conditions, several questions remain unanswered. One of them is the effect of missing observations on estimation performance. The presence of missing values in intensive longitudinal dataset decreases the number of observations per participant (or, more specifically, the number of observation-pairs that can be used for the estimation of the model). As such, it can be expected that lower compliance (i. e., lower proportion of ESM beeps that the given participant answered) will worsen the estimation bias. Additionally, different patterns of missingness might have different consequences on the estimation performance. Ji et al. [-@ji2018] show that the presence of data missing completely at random (MCAR), missing at random (MAR) and not missing at random (MNAR) leads to a considerable bias in point estimated of cross-lagged ant autoregressive parameters in vector autoregressive models when list-wise deletion is used. However, no similar evidence is available about the MLAR(1) model.

As such, the goal of the present thesis is to investigate whether compliance (or the proportion of missing data) and the different patterns of missingness have an effect on estimation bias, variability, and statistical power of the multilevel AR(1) model. Additionally, the number of participants *(N),* number of timepoints per participant *(T.obs),* the simulated fixed AR effect (\$\\beta\_{10}\$) and the variance of the random slopes/AR effects ( $\sigma_{\nu1}$) will be manipulated. More details about the simulation study are provided in the Methods section. In the remainder of the Introduction, I will present the evidence about compliance in ESM studies.

### Compliance and missing data in ESM studies

Due to the nature of intensive longitudinal data collection in psychology, the presence of missing data in the datasets is more of a rule than an exception. In their meta-analysis of 477 published ESM studies (with total *N* of 677,536), Wrzus and Nebauer [-@wrzus2022] found the average compliance to be 79.19% (*SD* = 13.64%). Importantly, both within-person, momentary factors (e. g., a participant might be less likely to answer an ESM beep during social situations, compared to when they are alone) and between-person factors could influence compliance.

On the study design level, compliance is usually higher in studies that provide financial incentives to participants [@vachon2019, @wrzus2022], while increasing questionnaire length is associated with lower compliance [@eisele2020]. On the other hand, sampling frequency (i. e., the number of 'beeps' per day) was not found to be associated with compliance in both an experimental study [@eisele2020] and a large-scale meta-analysis [@wrzus2022].

The evidence about participant characteristics associated with compliance is more ambiguous. While some studies found men to have lower compliance than women [@rintala2019, @vachon2019], the meta-analysis by Wrzus & Nebauer [-@wrzus2022] found the evidence for gender differences in compliance to be limited. Psychotic disorders appear to be associated with lower compliance [@vachon2019], and participants with depression tend to have higher compliance [@rintala2019]. Additionally, Rintala et al. [-@rintala2019] report that participants with higher overall positive affect and lower overall negative affect tend to have higher compliance. Furthermore, higher compliance was found to be associated with lower overall activity stress, lower event unpleasantness, feeling less physically tired/unwell, and using less alcohol [@rintala2020]. The evidence regarding the momentary factors of compliance is similarly limited. While Rintala [-@rintala2019] found some momentary measures (higher positive affect, feeling less disturbed by the ESM beep, and using tobacco) to be associated with higher compliance they conclude that the majority of the momentary factors are not correlated with compliance. Even though the evidence is limited, we can expect both within- and between-person differences in compliance to arise from a complex interaction of study design, sample characteristics and momentary.

To summarise the introductory part: I have introduced the application of the multilevel autoregressive model to operationalise inertia in ESM research, summarised the simulation studies about the statistical properties of the multilevel autoregressive model, and introduced the evidence about compliance in ESM research. In the rest of the thesis, I will describe the design, results and implications of two Monte Carlo simulation studies conducted to address the knowledge gap about the effect of missing data on the estimation performance of the multilevel autoregressive model.
