---
title: "summary"
author: "Benjamin Simsa (benjsimsa@gmail.com)"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Summary {.unlisted .unnumbered}

The multilevel autoregressive (MLAR) model represents one of the most popular methods for quantifying affective inertia, the resistance of affective processes to change. The present thesis aims to address a gap in knowledge about the effect of the presence of missing data on the statistical properties of the MLAR model. Although missed observations are common in intensive longidutinal datasets, none of the simulation studies that investigated the statistical properties of the MLAR model focused on this problem. 

In four simulation studies, we have investigated how the presence of different missing data patterns (missing completely at random, a block of consecutive missing observations, and the most extreme observations missing), together with different values of compliance (i.e., the proportion of non-missing observations), influences the estimation bias, standard error, and statistical power to detect the fixed slope of the MLAR model. 

The results suggest that when the lagged predictor is person-mean centered, the presence of missing data leads to an underestimation of the fixed autoregressive effect. The estimation bias is the worst for the conditions in which the most extreme observations are missing, and it is more severe when the compliance is low. However, the effect of missing data on estimation bias decreases as the number of timepoints (observations) per participant increases. The standard error is mostly influenced by the number of participants in the simulated dataset, and it is higher when the compliance is low. Similarly, the statistical power to detect the fixed autoregressive slope was found to be influenced by both compliance and the missingness pattern. These conclusions holds regardless of whether the random autoregressive effects are estimated included in the model or not. However, the supplementary simulations show that the bias is considerably smaller when the predictor is not person-mean centered. 

While we only explored a small subset of plausible simulation parameters in our studies, the reproducible simulation code is available online. This allows researchers to appraise the effect of missing data on the estimation in their planned study, and to take missing data into account when planning the sample size for their study. The results of the present thesis are also relevant for research design of intensive longitudinal studies. They suggest that if a precise estimation of inertia is the main research goal, motivating participants to high compliance and collecting more observations per participant might be more effective than collecting data from a larger number of participants. 