---
bibliography: references.bib
output:
  pdf_document
geometry: left = 2.5cm, right = 2.5cm, top = 2.5cm, bottom = 2.5cm
fontsize: 10pt
csl: apa.csl
indent: yes
always_allow_html: true
header-includes:
- \usepackage{float}
- \usepackage{sectsty}
- \usepackage{paralist}
- \usepackage{setspace}\spacing{1.5}
- \usepackage{lastpage}
- \usepackage{dcolumn}
- \usepackage[nottoc, numbib]{tocbibind}
- \usepackage{indentfirst}
- \usepackage{amsmath}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{=tex}
\allsectionsfont{\centering}
\subsectionfont{\raggedright}
\subsubsectionfont{\raggedright}
\pagenumbering{gobble}
```
```{=tex}
\begin{titlepage}

\begin{centering}
\vspace{6cm}
\Large
{\bf KU Leuven}

\Large
{\bf Faculty of Psychology and Educational Sciences}

\vspace{3cm}

\Large

\doublespacing
{\bf THE EFFECT OF MISSING DATA ON THE ESTIMATION BIAS, VARIANCE, AND STATISTICAL POWER IN MULTILEVEL AUTOREGRESSIVE(1) MODELS}

\end{centering}

\begin{flushright}
\vspace{5 cm}

\normalsize
\singlespacing

Master’s thesis submitted for the \linebreak
degree of Master of Science in \linebreak 
Master of Psychology: Theory and \linebreak 
Research by \linebreak 
\linebreak 
{\bf Benjamín Šimsa} \linebreak 
\linebreak 
\linebreak 
Supervisor: Prof. Dr. Eva Ceulemans \linebreak 
Co-supervisors: Dr. Ginette Lafit, Jordan Revol
\end{flushright}

\vspace{2 cm}

\centerline{2023}


\end{titlepage}

% TABLE OF CONTENTS

\pagenumbering{roman}

\newpage

\centering
\raggedright
\newpage
\tableofcontents

\setlength\parindent{24pt}
\pagenumbering{arabic}
```

\newpage

```{r introduction, child = 'intro.Rmd'}
```

\newpage

```{r methods, child = 'methods.Rmd'}
```

\newpage

```{r results, child = 'results.Rmd'}
```

\newpage

```{r discussion, child = 'discussion.Rmd'}
```

\newpage

```{r biblio, child = 'references.Rmd'}
```

\newpage

```{r supplementary, child = 'supplementary.Rmd'}
```
